#******************************************************************************
# Makefile<lib2>                                         Make-It-Quick project
#******************************************************************************
#
#  File Description:
#
#
#
#
#
#
#
#
#
#
#******************************************************************************
# (C) 2017-2018 Christophe de Dinechin <christophe@dinechin.org>
#     This software is licensed under the GNU General Public License v3
#     See LICENSE file for details.
#******************************************************************************

SOURCES=lib2.c
PRODUCTS=lib2.lib

BUILD?=make-it-quick/
include $(BUILD)rules.mk
