#******************************************************************************
# Makefile<lib1>                                         Make-It-Quick project
#******************************************************************************
#
#  File Description:
#
#   A simple example to build a small DLL
#
#
#
#
#
#
#
#
#******************************************************************************
# (C) 2017-2018 Christophe de Dinechin <christophe@dinechin.org>
#     This software is licensed under the GNU General Public License v3
#     See LICENSE file for details.
#******************************************************************************

SOURCES=lib1.c
PRODUCTS=lib1.dll

MIQ=../../
include $(MIQ)rules.mk
